name: Build Tailscale
on: [push]

jobs:
  build-tailscale:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          go mod download
      - name: Build Tailscale
        run: |
          go build -o tailscale.exe ./cmd/tailscaled
